# Generated by Django 4.2.4 on 2023-08-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_user_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidding_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='No Category Listed', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture_url',
            field=models.TextField(default="{% static 'auctions/img.png' %}", max_length=1000),
        ),
    ]
