# Generated by Django 4.2.4 on 2023-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_bidding_times_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='last_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidding_times',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture_url',
            field=models.TextField(max_length=1000),
        ),
    ]
