# Generated by Django 4.2.4 on 2023-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_last_bid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user_upload',
        ),
        migrations.AddField(
            model_name='listing',
            name='user_upload_id',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
