# Generated by Django 4.2.4 on 2023-08-29 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_user_upload_listing_user_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='user_upload_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
