# Generated by Django 4.2.4 on 2023-08-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_user_upload_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user_upload_id',
            new_name='user_upload',
        ),
    ]
