# Generated by Django 4.2.4 on 2023-08-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_user_upload_id_listing_user_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_in_watch_list',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
